apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-phim-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  PGPOOL_HOST: "${PGPOOL_HOST}"
  PGPOOL_DB: "${PGPOOL_DB}"
  PGPOOL_USER: "${PGPOOL_USER}"
  PGPOOL_PORT: "${PGPOOL_PORT}"
  PGPOOL_URL: "${PGPOOL_URL}"
  JWT_ALGORITHM: "${JWT_ALGORITHM}"
  JWT_EXPIRE: "${JWT_EXPIRE}"
  ALLOWED_DOMAINS: "${ALLOWED_DOMAINS}"
  GLOBAL_DOMAIN: "${GLOBAL_DOMAIN}"
  AUTHORIZATION_SERVICE_URL: "${AUTHORIZATION_SERVICE_URL}"
  UPLOAD_SERVICE_URL: "${UPLOAD_SERVICE_URL}"
  CDN_SERVICE_URL: "${CDN_SERVICE_URL}"
  MEILISEARCH_HOST: "${MEILISEARCH_HOST}"
  REDIS_ADDRESS: "${REDIS_ADDRESS}"
  REDIS_DB: "${REDIS_DB}"
  SERVER_PORT: "8080"
  SERVER_HOST: "0.0.0.0"
  ENVIRONMENT_MODE: "${ENVIRONMENT_MODE}"
  ENVIRONMENT_GROUP: "${ENVIRONMENT_GROUP}"
  SERVICE_NAME: "gau-phim-service"
