apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-phim-frontend-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  SERVERSIDE_API: "${SERVERSIDE_API}"
  JWT_SECRET: "${JWT_SECRET}"
  PRIVATE_KEY: "${PRIVATE_KEY}"
  PORT: "${PORT}"

