name: deploy-staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and authenticate
        run: |
          sudo tailscaled &
          sleep 3
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          sleep 5

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create staging dir and download .env from server
        run: |
          mkdir -p ./deploy/k8s/staging
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/tnqbao/.enviroment/gau-phim-frontend/serverside.env ./deploy/k8s/staging/.env

      - name: Download kubeconfig.yaml from server
        run: |
          mkdir -p ./deploy/k8s/staging
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/.secret/k8s/kubeconfig.yaml ./deploy/k8s/staging/kubeconfig.yaml

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=${GITHUB_WORKSPACE}/deploy/k8s/staging/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Check Kubernetes access
        run: kubectl get nodes

      - name: Make scripts executable
        run: |
          chmod +x ./deploy/k8s/staging/apply.sh
          chmod +x ./deploy/k8s/staging/apply_envsubst.sh || true

      - name: Apply manifests to Kubernetes
        working-directory: ./deploy/k8s/staging
        run: ./apply.sh

      - name: Check active pods
        run: kubectl get pods -n bao-staging-env

      - name: Restart pods
        run: |
          kubectl rollout restart deployment gau-phim-frontend-deployment -n bao-staging-env
          sleep 10
          kubectl get pods -n bao-staging-env
